---
- hosts: localhost
  gather_facts: no
  roles:
     - role: vault-load-config
       become: yes

     - role: ansible-kubernetes-modules
       install_python_requirements: no

     - role: prometheus-operator
